=== DdPokk/ITMO-HTML-XML/XML practice/lesssons_DTD.dtd
<!ELEMENT lessons (lesson+)>
<!ELEMENT lesson (Title, LastNameTeacher, FirstNameTeacher, DateStart, DateEnd, Time)>
<!ELEMENT Title (#PCDATA)> 
<!ELEMENT LastNameTeacher (#PCDATA)> 
<!ELEMENT FirstNameTeacher (#PCDATA)> 
<!ELEMENT DateStart (#PCDATA)> 
<!ELEMENT DateEnd (#PCDATA)> 
<!ELEMENT Time (#PCDATA)>

=== DdPokk/ITMO-HTML-XML/XML practice/lesssons.xml
<?xml version = "1.0" encoding ="utf-8"?>
<!DOCTYPE lessons SYSTEM "lesssons_DTD.dtd" >
<lessons>
	<lesson id="a">
		<Title>Физика</Title>
		<LastNameTeacher>Иванов</LastNameTeacher>
		<FirstNameTeacher>Петр</FirstNameTeacher>
		<DateStart>02.02.2022</DateStart>
		<DateEnd>31.05.2000</DateEnd>
		<Time>09.00</Time>
	</lesson>
</lessons>
